apiVersion: v1
kind: Service
metadata:
  name: frontend-mobile
  namespace: tree-hollow
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30517
      name: http
  selector:
    app: frontend-mobile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-mobile
  namespace: tree-hollow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-mobile
  template:
    metadata:
      labels:
        app: frontend-mobile
    spec:
      containers:
        - name: frontend
          image: tree-hollow-mobile:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: {path: /, port: 80}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests: {cpu: "50m", memory: "32Mi"}
            limits: {cpu: "200m", memory: "128Mi"}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-admin
  namespace: tree-hollow
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30518
      name: http
  selector:
    app: frontend-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-admin
  namespace: tree-hollow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-admin
  template:
    metadata:
      labels:
        app: frontend-admin
    spec:
      containers:
        - name: frontend
          image: tree-hollow-admin:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: {path: /, port: 80}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests: {cpu: "50m", memory: "32Mi"}
            limits: {cpu: "200m", memory: "128Mi"}
